# portainer installation

version: '3'
services:
  portainer:
    image: "portainer/portainer-ce:latest"
    ports:
      - "8000:8000"
      - "9443:9443"
    restart: always
    privileged: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
volumes:
  portainer_data: